spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.url=jdbc:postgresql://localhost:5432/tsinjo_std22090
spring.datasource.username=postgres
spring.datasource.password=rina0109!
logging.level.org.flywaydb=DEBUG
